// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// prettier-ignore

declare module "class-types.macro" {
  // prettier-ignore
  export default function ct<T extends ClassTypes>(...a: T[]): T;
}
